#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRES
xrdb $HOME/.Xresources
xsetroot -solid grey
xterm -geometry 640x480 -ls -title "$VNCDESKTOP Desktop" &
x-window-manager &
# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1
/etc/X11/Xsession

vncconfig -iconic &
gnome-panel &
gnome-settings-daemon &
metacity &
nautilus &
gnome-session &
